version: '2.4'

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-jcr:latest
    container_name: artifactory
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./artifactory/:/artifactory_extra_conf/
    restart: always
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8082/artifactory/api/system/ping"]
        start_period: 30s
        interval: 5s
        timeout: 10s
        retries: 30

  jenkins:
    depends_on:
      artifactory:
        condition: service_healthy
    build: jenkins_controller
    container_name: jenkins
    ports:
      - "50000:50000"
      - "8880:8080"
    volumes:
      - ./jenkins_controller/casc.yaml:/usr/share/jenkins/ref/casc.yaml
    restart: always

  jenkins_agent:
    depends_on:
      - jenkins
    container_name: jenkins_agent
    build: jenkins_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2222:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC66Sb2sWAgIrg9JNz0H6rLP0CUpIQAQCv6bf/Uvoh5yX60OS1Ns1SjGXbT4RFabHoqn+IDckQ8MJiWaQAIy1/9B4fpTthfAxyQBC8vqBmGRdQm4MdNKhZOFgw0m8gpkp9EQH8H8b7oBOBY3/wBi5siZmOLFH1jh7FiNdKbts8FBrDi6U1b+uq2MvV56tbttXf2v/O+8JPgs1rkg2tQIcRjVdL4yK+B4jKgKqpH4I6tmsN0yYo00AGdILgEaPFfnNdxhS+gZoYgr/d90T1CuPY0+wsqFk+iV0Jh7yq7k65jUxRxEdOjfmUZsckAt0lH0jxKrL21hwY4nzvILyKAM2RayQGtaO9KbBveWtkbFytJDCBJLXLQZBCYO+7OXgxY742ta+y8vLS+EeBnkykINgV7MA1485EAoW0jGCfNOUJW4X323uazX7dVyDEglJb/3Qa/dmn85/0UwpNruiXfi4XmaoOyyQdT1HWkTJ3kTp1uki59C3aK9UhN445uxGupFmk=
    restart: always

  sonarqube:
    depends_on:
      - jenkins
    image: sonarqube:9.2.4-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    restart: always

  selenium_hub:
    depends_on:
      - jenkins
    image: selenium/hub
    container_name: selenium_hub
    ports:
    - "4442:4442"
    - "4443:4443"
    - "4444:4444"
    restart: always

  firefox:
    image: selenium/node-firefox
    container_name: firefox
    depends_on:
      - selenium_hub
    environment:
    - SE_EVENT_BUS_HOST=selenium_hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    restart: always